Controllers/API/ApiEventosController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using GerenciamentoEvento.Data;
using GerenciamentoEvento.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiRest.Controllers {
    [Route ("api/v1/eventos")]
    [ApiController]
    public class EventosController : ControllerBase {

        private readonly ApplicationDbContext database;

        public EventosController (ApplicationDbContext database) {

            this.database = database;
        }

        /// <summary>
        /// Listar Eventos
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Get () {
            var eventos = database.Evento.Include (e => e.CasaDeShow).Where (p => p.CasaDeShow.Status == true).Where (p => p.Status == true).Where (p => p.CasaDeShow.Status == true).ToList ();
            return Ok (eventos); //Status code = 200 && Dados 
        }
        /// <summary>
        /// Listar eventos por capacidade ascendente
        /// </summary>
        /// <returns></returns>
        [HttpGet ("capacidade/asc")]
        public IActionResult GetAsc () {
            var local = database.Evento.Include (e => e.CasaDeShow).Where (p => p.CasaDeShow.Status == true).Where (p => p.Status == true).ToList ().OrderBy (p => p.Capacidade);
            return Ok (local);
            //Status code = 200 && Dados 

        }
        /// <summary>
        /// Listar eventos por capacidade descendente
        /// </summary>
        /// <returns></returns>
        [HttpGet ("capacidade/desc")]
        public IActionResult GetDesc () {
            var local = database.Evento.Include (e => e.CasaDeShow).Where (p => p.CasaDeShow.Status == true).Where (p => p.Status == true).ToList ().OrderByDescending (p => p.Capacidade);
            return Ok (local);
            //Status code = 200 && Dados 

        }
        /// <summary>
        /// Listar eventos por data ascendente
        /// </summary>
        /// <returns></returns>
        [HttpGet ("data/asc")]
        public IActionResult GetDataAsc () {
            var local = database.Evento.Include (e => e.CasaDeShow).Where (p => p.CasaDeShow.Status == true).Where (p => p.Status == true).ToList ().OrderBy (p => p.Data);
            return Ok (local);
            //Status code = 200 && Dados 

        }
        /// <summary>
        /// Listar eventos por data descendente
        /// </summary>
        /// <returns></returns>
        [HttpGet ("data/desc")]
        public IActionResult GetDataDesc () {
            var local = database.Evento.Include (e => e.CasaDeShow).Where (p => p.CasaDeShow.Status == true).Where (p => p.Status == true).ToList ().OrderByDescending (p => p.Data);
            return Ok (local);
            //Status code = 200 && Dados 
        }
        /// <summary>
        /// Listar eventos por preço ascendente
        /// </summary>
        /// <returns></returns>
        [HttpGet ("preco/asc")]
        public IActionResult GetPrecoAsc () {
            var local = database.Evento.Include (e => e.CasaDeShow).Where (p => p.CasaDeShow.Status == true).Where (p => p.Status == true).ToList ().OrderBy (p => p.Preco);
            return Ok (local);
            //Status code = 200 && Dados 

        }

        /// <summary>
        /// Listar eventos por preço descendente
        /// </summary>
        /// <returns></returns>
        [HttpGet ("preco/desc")]
        public IActionResult GetPrecoDesc () {
            var local = database.Evento.Include (e => e.CasaDeShow).Where (p => p.CasaDeShow.Status == true).Where (p => p.Status == true).ToList ().OrderByDescending (p => p.Preco);
            return Ok (local);
            //Status code = 200 && Dados 
        }
        /// <summary>
        /// Listar eventos por nome ascendente
        /// </summary>
        /// <returns></returns>
        [HttpGet ("nome/asc")]
        public IActionResult GetNomeAsc () {
            var local = database.Evento.Include (e => e.CasaDeShow).Where (p => p.CasaDeShow.Status == true).Where (p => p.Status == true).ToList ().OrderBy (p => p.Nome);
            return Ok (local);
        }
        /// <summary>
        /// Listaer eventos por nome descendente
        /// </summary>
        /// <returns></returns>
        [HttpGet ("nome/desc")]
        public IActionResult GetNomeDesc () {
            var local = database.Evento.Include (e => e.CasaDeShow).Where (p => p.CasaDeShow.Status == true).Where (p => p.Status == true).ToList ().OrderByDescending (p => p.Nome);
            return Ok (local);
        }
        /// <summary>
        /// Listar eventos por ID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet ("{id}")]
        public IActionResult Get (int id) {
            try {
                Evento evento = database.Evento.Include (e => e.CasaDeShow).Where (p => p.CasaDeShow.Status == true).Where (e => e.Status == true).First (p => p.Id == id);
                return Ok (evento);
            } catch (Exception) {

                Response.StatusCode = 404;
                return new ObjectResult (new { msg = "ID Inválido" });
            }

        }

        /// <summary>
        /// Criar eventos (Necessita Autorização)
        /// </summary>
        /// <param name="eTemp"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public IActionResult Post ([FromBody] EventoTemp eTemp) {
            //Validação
            if (eTemp != null) {
                try {
                    if (eTemp.CasaDeShowID == 0) {
                        return new ObjectResult (new { msg = "O Local do Evento não existe!" });
                    }
                    Evento e = new Evento ();
                    e.Nome = eTemp.Nome;
                    e.Capacidade = eTemp.Capacidade;
                    e.Data = eTemp.Data;
                    e.Preco = eTemp.Preco;
                    e.CasaDeShow = database.Local.First (c => c.Id == eTemp.CasaDeShowID);
                    e.Estilo = eTemp.Estilo.ToString ();
                    e.Imagem = eTemp.Imagem;
                    e.Status = eTemp.Status;
                    database.Evento.Add (e);
                    database.SaveChanges ();

                    //Set do Status Code
                    Response.StatusCode = 201;
                    return new ObjectResult (new { msg = "Evento criado com sucesso!" });
                } catch (Exception) {
                    Response.StatusCode = 400;
                    return BadRequest (new { msg = "Verifique se o ID do evento está correto" });
                }
            }
            return BadRequest (new { msg = "Verifique se as informações do evento estão corretas" });
        }
        /// <summary>
        /// Atualizar evento (Necessita Autorização)
        /// </summary>
        /// <param name="ptemp"></param>
        /// <returns></returns>
        [HttpPatch]
        [Authorize]
        public IActionResult Patch ([FromBody] EventoPatch ptemp) {

            if (ptemp.Id >= 0) {

                try {
                    var evento = database.Evento.First (p => p.Id == ptemp.Id);
                    //Editar 
                    if (ptemp.Nome != null) {
                        if (ptemp.Nome.Length > 2 && ptemp.Nome.Length < 150) {
                            evento.Nome = ptemp.Nome;
                        } else {
                            evento.Nome = evento.Nome;
                            Response.StatusCode = 404;
                            return new ObjectResult (new { msg = "Nome Inválido" });
                        }
                    }
                    if (ptemp.Capacidade != 0) {
                        if (ptemp.Capacidade > 10 && ptemp.Capacidade < 1000000) {
                            evento.Capacidade = ptemp.Capacidade;
                        } else {
                            evento.Capacidade = evento.Capacidade;
                            Response.StatusCode = 404;
                            return new ObjectResult (new { msg = "Capaidade Inválida" });
                        }
                    }
                    if (ptemp.Preco != 0) {
                        if (ptemp.Preco > 10 || ptemp.Preco < 1000000) {
                            evento.Preco = ptemp.Preco;
                        } else {
                            evento.Preco = evento.Preco;
                            Response.StatusCode = 404;
                            return new ObjectResult (new { msg = "Preço Inválida" });
                        }
                    }

                    if (ptemp.CasaDeShowID != 0) {
                        if (database.Local.First (p => p.Id == ptemp.CasaDeShowID) != null) {
                            evento.CasaDeShow = database.Local.First (p => p.Id == ptemp.CasaDeShowID);
                        } else {
                            Response.StatusCode = 404;
                            return new ObjectResult (new { msg = "Local de inválido" });
                        }
                    }
                    if (ptemp.Estilo != 0) {
                        if (evento.Estilo == ptemp.Estilo.ToString () && ptemp.Estilo > 0 || ptemp.Estilo < 8) {
                            evento.Estilo = ptemp.Estilo.ToString ();
                        } else {
                            evento.Estilo = evento.Estilo;
                            Response.StatusCode = 404;
                            return new ObjectResult (new { msg = "Estilo de Inválido" });
                        }
                    }

                    if (ptemp.Imagem != null) {
                        if (ptemp.Imagem.Length > 10 && ptemp.Imagem.Length < 1024) {
                            evento.Imagem = ptemp.Imagem;
                        } else {
                            evento.Imagem = evento.Imagem;

Controllers/API/ApiLocalController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Http;
using GerenciamentoEvento.Data;
using GerenciamentoEvento.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Projeto_Casa.Controllers.API {

    [Route ("api/v1/local")]
    [ApiController]

    public class LocalController : ControllerBase {
        private readonly ApplicationDbContext database;

        public LocalController (ApplicationDbContext database) {

            this.database = database;
        }
        /// <summary>
        /// Listar Local 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Get () {
            var local = database.Local.Where (p => p.Status == true).ToList ();
            return Ok (local);
            //Status code = 200 && Dados 
        }

        /// <summary>
        /// Listar local por nome ascendente
        /// </summary>
        /// <returns></returns>
        [HttpGet ("asc")]
        public IActionResult GetAsc () {
            var local = database.Local.Where (p => p.Status == true).ToList ().OrderBy (p => p.Nome);
            return Ok (local);
            //Status code = 200 && Dados 

        }
        /// <summary>
        /// Listar Local por nome decrescente
        /// </summary>
        /// <returns></returns>
        [HttpGet ("desc")]
        public IActionResult GetDesc () {
            var local = database.Local.Where (p => p.Status == true).ToList ().OrderByDescending (p => p.Nome);
            return Ok (local);
            //Status code = 200 && Dados 

        }
        /// <summary>
        /// Listar Local por ID 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet ("{id}")]
        public IActionResult GetId (int id) {
            try {
                var local = database.Local.Where (l => l.Status == true).First (l => l.Id == id);
                return Ok (local);
            } catch (Exception) {

                Response.StatusCode = 404;
                return new ObjectResult (new { msg = "ID inválido" });
            }

        }
        /// <summary>
        /// Listar Local por Nome
        /// </summary>
        /// <param name="nome"></param>
        /// <returns></returns>
        [HttpGet ("nome/" + "{nome}")]
        public IActionResult GetNome (string nome) {
            try {
                var local = database.Local.Where (l => l.Status == true).First (l => l.Nome.ToLower () == nome.ToLower ());
                return Ok (local);
            } catch (Exception) {

                Response.StatusCode = 404;
                return new ObjectResult (new { msg = "Nome Inválido" });
            }

        }

        /// <summary>
        /// Criar Local (Necessita Autorização)
        /// </summary>
        /// <param name="lTemp"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public IActionResult Post ([FromBody] LocalTemp lTemp) {
            try {
                Local l = new Local ();
                l.Nome = lTemp.Nome;
                l.Endereco = lTemp.Endereco;
                l.LinkEndereco = lTemp.LinkEndereco;
                l.Status = true;
                database.Local.Add (l);
                database.SaveChanges ();

                //Set do Status Code
                Response.StatusCode = 201;
                return new ObjectResult (new { msg = "Local criado com sucesso!" });
            } catch {
                return BadRequest (new { msg = "ID Inválido" });
            }
        }

        /// <summary>
        /// Atualizar local (Necessita Autorização)
        /// </summary>
        /// <param name="ltemp"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPatch]
        public IActionResult Patch ([FromBody] LocalPatch ltemp) {

            if (ltemp.Id >= 0) {
                try {
                    var local = database.Local.First (p => p.Id == ltemp.Id);
                    //Editar 
                    if (ltemp.Nome != null) {
                        if (ltemp.Nome.Length > 0 && ltemp.Nome.Length < 100) {
                            local.Nome = ltemp.Nome;
                        } else {
                            Response.StatusCode = 404;
                            return new ObjectResult (new { msg = "Nome  inválido" });
                        }
                    }

                    if (ltemp.Endereco != null) {
                        if (ltemp.Endereco.Length > 0 && ltemp.Endereco.Length < 100) {
                            local.Endereco = ltemp.Endereco;
                        } else {
                            Response.StatusCode = 404;
                            return new ObjectResult (new { msg = "Endereço  inválido" });
                        }
                    }
                    if (ltemp.LinkEndereco != null) {
                        if (ltemp.LinkEndereco.Length > 0 && ltemp.LinkEndereco.Length < 1024) {
                            local.LinkEndereco = ltemp.LinkEndereco;
                        } else {
                            Response.StatusCode = 404;
                            return new ObjectResult (new { msg = "Url  inválida" });
                        }
                    }
                    database.SaveChanges ();
                    return Ok (new { msg = "Local Atualilzado!" });

                } catch (System.Exception) {
                    Response.StatusCode = 404;
                    return new ObjectResult (new { msg = "Requisição Inválida!" });
                }

            } else {
                Response.StatusCode = 404;
                return new ObjectResult (new { msg = "ID inválido" });
            }
        }

        /// <summary>
        /// Deletar Local (Necessita Autorização)
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>   
        [Authorize]
        [HttpDelete ("{id}")]
        public IActionResult Delete (int id) {
            try {
                var local = database.Local.First (p => p.Id == id);
                local.Status = false;
                database.SaveChanges ();
                Response.StatusCode = 201;
                return new ObjectResult (new { msg = "Local excluido!" });
            } catch (Exception) {

                Response.StatusCode = 404;
                return new ObjectResult (new { msg = "Id inválido" });
            }
        }
        public class LocalTemp {

            [Required]
            public int Id { get; set; }

            [Required (ErrorMessage = "O Nome é obrigatório.")]
            public string Nome { get; set; }

            [Required (ErrorMessage = "O Endereço é obrigatório.")]
            public string Endereco { get; set; }

            public string LinkEndereco { get; set; }

            public bool Status { get; set; }
        }
        public class LocalPatch {
            public int Id { get; set; }
            public string Nome { get; set; }
            public string Endereco { get; set; }
            public string LinkEndereco { get; set; }

        }
    }

}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<style>
#titulo{
    font-family: 'Monoton', cursive;
    font-size:48px
    
}



#slider {
    height: 600px;
    overflow: hidden;
}

#icon{height: 50%;}

th{text-align: center;}

label{margin-top: 20px;}


</style>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eventos.com</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Bebas+Neue|Monoton|Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans&display=swap" rel="stylesheet">

    <!-----Carregamento Jquerry----->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>


  </head>

<style>
body{
    background-color: whitesmoke;
    font-family: 'Bebas Neue', cursive;
     }
</style>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-family: 'Monoton', cursive;"> Eventos.com </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eventos" asp-action="Home">Shows!</a>
                        </li>
                       
                        @* Validação para administrador *@
                        @if( SignInManager.IsSignedIn(User) && User.Identity.Name == "admin@gmail.com"){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eventos" asp-action="Index">Eventos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Local" asp-action="Index">Locais</a>
                        </li>
                    <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Api
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" asp-area="" asp-controller="Local" asp-action="GetLocal">Local</a>
                    <a class="dropdown-item" asp-area="" asp-controller="Eventos" asp-action="GetEventos">Eventos</a>
                        </div>
                 </div>  
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - ASP.NET Core Application by Guilherme Azevedo - <a href="https://github.com/gui-azesantos">Github</a>
        </div>
        <div>
            
        
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>